/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotifikasiRouteImport } from './routes/notifikasi'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaporRouteImport } from './routes/lapor'
import { Route as BerandaRouteImport } from './routes/beranda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LaporIndexRouteImport } from './routes/lapor.index'
import { Route as LaporTemuanRouteImport } from './routes/lapor.temuan'
import { Route as LaporHilangRouteImport } from './routes/lapor.hilang'
import { Route as DetailIdRouteImport } from './routes/detail.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifikasiRoute = NotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporRoute = LaporRouteImport.update({
  id: '/lapor',
  path: '/lapor',
  getParentRoute: () => rootRouteImport,
} as any)
const BerandaRoute = BerandaRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporIndexRoute = LaporIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LaporRoute,
} as any)
const LaporTemuanRoute = LaporTemuanRouteImport.update({
  id: '/temuan',
  path: '/temuan',
  getParentRoute: () => LaporRoute,
} as any)
const LaporHilangRoute = LaporHilangRouteImport.update({
  id: '/hilang',
  path: '/hilang',
  getParentRoute: () => LaporRoute,
} as any)
const DetailIdRoute = DetailIdRouteImport.update({
  id: '/detail/$id',
  path: '/detail/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beranda': typeof BerandaRoute
  '/lapor': typeof LaporRouteWithChildren
  '/login': typeof LoginRoute
  '/notifikasi': typeof NotifikasiRoute
  '/register': typeof RegisterRoute
  '/detail/$id': typeof DetailIdRoute
  '/lapor/hilang': typeof LaporHilangRoute
  '/lapor/temuan': typeof LaporTemuanRoute
  '/lapor/': typeof LaporIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beranda': typeof BerandaRoute
  '/login': typeof LoginRoute
  '/notifikasi': typeof NotifikasiRoute
  '/register': typeof RegisterRoute
  '/detail/$id': typeof DetailIdRoute
  '/lapor/hilang': typeof LaporHilangRoute
  '/lapor/temuan': typeof LaporTemuanRoute
  '/lapor': typeof LaporIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beranda': typeof BerandaRoute
  '/lapor': typeof LaporRouteWithChildren
  '/login': typeof LoginRoute
  '/notifikasi': typeof NotifikasiRoute
  '/register': typeof RegisterRoute
  '/detail/$id': typeof DetailIdRoute
  '/lapor/hilang': typeof LaporHilangRoute
  '/lapor/temuan': typeof LaporTemuanRoute
  '/lapor/': typeof LaporIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beranda'
    | '/lapor'
    | '/login'
    | '/notifikasi'
    | '/register'
    | '/detail/$id'
    | '/lapor/hilang'
    | '/lapor/temuan'
    | '/lapor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beranda'
    | '/login'
    | '/notifikasi'
    | '/register'
    | '/detail/$id'
    | '/lapor/hilang'
    | '/lapor/temuan'
    | '/lapor'
  id:
    | '__root__'
    | '/'
    | '/beranda'
    | '/lapor'
    | '/login'
    | '/notifikasi'
    | '/register'
    | '/detail/$id'
    | '/lapor/hilang'
    | '/lapor/temuan'
    | '/lapor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BerandaRoute: typeof BerandaRoute
  LaporRoute: typeof LaporRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotifikasiRoute: typeof NotifikasiRoute
  RegisterRoute: typeof RegisterRoute
  DetailIdRoute: typeof DetailIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifikasi': {
      id: '/notifikasi'
      path: '/notifikasi'
      fullPath: '/notifikasi'
      preLoaderRoute: typeof NotifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lapor': {
      id: '/lapor'
      path: '/lapor'
      fullPath: '/lapor'
      preLoaderRoute: typeof LaporRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beranda': {
      id: '/beranda'
      path: '/beranda'
      fullPath: '/beranda'
      preLoaderRoute: typeof BerandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lapor/': {
      id: '/lapor/'
      path: '/'
      fullPath: '/lapor/'
      preLoaderRoute: typeof LaporIndexRouteImport
      parentRoute: typeof LaporRoute
    }
    '/lapor/temuan': {
      id: '/lapor/temuan'
      path: '/temuan'
      fullPath: '/lapor/temuan'
      preLoaderRoute: typeof LaporTemuanRouteImport
      parentRoute: typeof LaporRoute
    }
    '/lapor/hilang': {
      id: '/lapor/hilang'
      path: '/hilang'
      fullPath: '/lapor/hilang'
      preLoaderRoute: typeof LaporHilangRouteImport
      parentRoute: typeof LaporRoute
    }
    '/detail/$id': {
      id: '/detail/$id'
      path: '/detail/$id'
      fullPath: '/detail/$id'
      preLoaderRoute: typeof DetailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LaporRouteChildren {
  LaporHilangRoute: typeof LaporHilangRoute
  LaporTemuanRoute: typeof LaporTemuanRoute
  LaporIndexRoute: typeof LaporIndexRoute
}

const LaporRouteChildren: LaporRouteChildren = {
  LaporHilangRoute: LaporHilangRoute,
  LaporTemuanRoute: LaporTemuanRoute,
  LaporIndexRoute: LaporIndexRoute,
}

const LaporRouteWithChildren = LaporRoute._addFileChildren(LaporRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BerandaRoute: BerandaRoute,
  LaporRoute: LaporRouteWithChildren,
  LoginRoute: LoginRoute,
  NotifikasiRoute: NotifikasiRoute,
  RegisterRoute: RegisterRoute,
  DetailIdRoute: DetailIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
